stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - gem build ./glycobook.gemspec

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - gem install glycobook-0.0.1.gem
    - ruby sample.rb

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file glycobook.gemspec "https://gitlab.example.com/api/v4/projects/45174010/packages/gem"
